version: '3'

services:
  app:
    environment:
      - GOOGLE_ANALYTICS_KEY=${GOOGLE_ANALYTICS_KEY}
    restart: always
    container_name: app
    build:
      context: .
    volumes:
      - ./sampleproj:/app/sampleproj
      - ./prereq_map:/app/prereq_map
    ports:
      - "8000:8000"
  devtools:
    restart: always
    container_name: devtools
    image: node:8.15.1-jessie
    volumes:
      - ./package.json:/devtools/prereq-map/package.json
      - ./webpack.config.js:/devtools/prereq-map/webpack.config.js
      - ./prereq_map:/devtools/prereq-map/prereq_map
    working_dir: /devtools/prereq-map
    command: bash -c "yes yes | npm install; npx webpack --watch --mode=development"
