version: '3'

services:
  app:
    environment:
      - GOOGLE_ANALYTICS_KEY=${GOOGLE_ANALYTICS_KEY}
    restart: always
    container_name: prereq_map_app
    build:
      context: .
    volumes:
      - ./prereq_map:/prereq_map_app/prereq_map
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
  dev:
    restart: always
    container_name: prereq_map_dev
    image: node:8.16.0-jessie
    volumes:
      - ./package.json:/prereq_map_dev/prereq-map/package.json
      - ./webpack.config.js:/prereq_map_dev/prereq-map/webpack.config.js
      - ./prereq_map:/prereq_map_dev/prereq-map/prereq_map
    working_dir: /prereq_map_dev/prereq-map
    command: bash -c "yes yes | npm install; npx webpack --watch --mode=development"
