version: '3'

services:
  app:
    restart: always
    build: .
    # map the local (host) directories to their container counterparts
    # to support live-syncing
    volumes:
      - ./sampleproj:/app/sampleproj
      - ./prereq_map:/app/prereq_map
      - ./webpack-stats.json:/app/webpack-stats.json
    ports:
      - "8123:8123"
    command: bash -c "python manage.py migrate --settings=sampleproj.settings.local_defaults && python manage.py runserver 0.0.0.0:8123 --settings=sampleproj.settings.local_defaults"
