version: '3'

services:
  app:
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: Dockerbase
    volumes:
      - ./sampleproj:/app/sampleproj
      - ./prereq_map:/app/prereq_map
    ports:
      - "8000:8000"
    command: bash -c ". /app/bin/activate && python manage.py migrate --settings=sampleproj.settings.local_defaults && python manage.py loaddata curric_titles.json --settings=sampleproj.settings.local_defaults && python manage.py runserver 0.0.0.0:8000 --settings=sampleproj.settings.local_defaults"
  devtools:
    restart: always
    container_name: devtools
    image: node:8.15.1-jessie
    volumes:
      - ./package.json:/devtools/prereq-map/package.json
      - ./webpack.config.js:/devtools/prereq-map/webpack.config.js
      - ./prereq_map:/devtools/prereq-map/prereq_map
    working_dir: /devtools/prereq-map
    command: bash -c "yes yes | npm install; npx webpack --watch"
