version: '3'

services:
  app:
    restart: always
    build: .
    # map the local (host) directories to their container counterparts
    # to support live-syncing
    volumes:
      - ./sampleproj:/app/sampleproj
      - ./prereq_map:/app/prereq_map
      #- ./webpack-stats.json:/app/webpack-stats.json
    ports:
      - "8000:8000"
    command: bash -c ". /app/bin/activate && python manage.py migrate --settings=sampleproj.settings.local && python manage.py loaddata curric_titles.json --settings=sampleproj.settings.local && python manage.py runserver 0.0.0.0:8000 --settings=sampleproj.settings.local"
