version: '3'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerbase
    volumes:
      - ./sampleproj:/app/sampleproj
      - ./prereq_map:/app/prereq_map
    ports:
      - "8000:8000"
    command: bash -c ". /app/bin/activate && python manage.py migrate --settings=sampleproj.settings.local_defaults && python manage.py loaddata curric_titles.json --settings=sampleproj.settings.local_defaults && python manage.py runserver 0.0.0.0:8000 --settings=sampleproj.settings.local_defaults"
