# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.1.2 on 2019-01-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_abbrev', models.CharField(max_length=6)),
                ('course_number', models.SmallIntegerField()),
                ('last_eff_yr', models.SmallIntegerField()),
                ('last_eff_qtr', models.SmallIntegerField()),
                ('course_branch', models.SmallIntegerField()),
                ('course_college', models.CharField(max_length=1)),
                ('long_course_title', models.CharField(max_length=120)),
                ('prq_lang_of_adm', models.SmallIntegerField()),
                ('prq_check_grads', models.CharField(max_length=1)),
                ('pre_cancel_req', models.CharField(max_length=1)),
                ('course_cat_omit', models.BooleanField()),
                ('writing_crs', models.BooleanField()),
                ('diversity_crs', models.BooleanField()),
                ('english_comp', models.BooleanField()),
                ('qsr', models.BooleanField()),
                ('vis_lit_perf_arts', models.BooleanField()),
                ('indiv_society', models.BooleanField()),
                ('natural_world', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_branch', models.SmallIntegerField()),
                ('department_abbrev', models.CharField(max_length=32)),
                ('course_number', models.SmallIntegerField()),
                ('last_eff_year', models.SmallIntegerField()),
                ('last_eff_qtr', models.CharField(max_length=6)),
                ('pr_seq_no', models.SmallIntegerField()),
                ('pr_curric_abbr', models.CharField(max_length=32)),
                ('pr_course_no', models.SmallIntegerField()),
                ('pr_group_no', models.SmallIntegerField()),
                ('pr_and_or', models.CharField(max_length=3)),
                ('pr_cr_s', models.BooleanField()),
                ('pr_concurrency', models.BooleanField()),
            ],
        ),
    ]
