# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.1.2 on 2019-02-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prereq_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurricTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=40)),
                ('campus', models.SmallIntegerField(choices=[(0, 'Seattle'), (1, 'Bothell'), (2, 'Tacoma')])),
            ],
        ),
    ]
