# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.1.2 on 2019-03-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prereq_map', '0002_currictitles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetitle',
            name='course_branch',
        ),
        migrations.RemoveField(
            model_name='coursetitle',
            name='course_cat_omit',
        ),
        migrations.RemoveField(
            model_name='coursetitle',
            name='diversity_crs',
        ),
        migrations.RemoveField(
            model_name='coursetitle',
            name='english_comp',
        ),
        migrations.RemoveField(
            model_name='coursetitle',
            name='indiv_society',
        ),
        migrations.RemoveField(
            model_name='coursetitle',
            name='last_eff_qtr',
        ),
        migrations.RemoveField(
            model_name='coursetitle',
            name='last_eff_yr',
        ),
        migrations.RemoveField(
            model_name='coursetitle',
            name='natural_world',
        ),
        migrations.RemoveField(
            model_name='coursetitle',
            name='pre_cancel_req',
        ),
        migrations.RemoveField(
            model_name='coursetitle',
            name='prq_check_grads',
        ),
        migrations.RemoveField(
            model_name='coursetitle',
            name='prq_lang_of_adm',
        ),
        migrations.RemoveField(
            model_name='coursetitle',
            name='qsr',
        ),
        migrations.RemoveField(
            model_name='coursetitle',
            name='vis_lit_perf_arts',
        ),
        migrations.RemoveField(
            model_name='coursetitle',
            name='writing_crs',
        ),
    ]
