# Generated by Django 2.1.7 on 2019-04-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prereq_map', '0004_coursegraph_curricgraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegraph',
            name='build_hash',
            field=models.CharField(default='97bc592b27a9ada2d9a4bb418ed0ebed', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curricgraph',
            name='build_hash',
            field=models.CharField(default='97bc592b27a9ada2d9a4bb418ed0ebed', max_length=32),
            preserve_default=False,
        ),
    ]
