version: '3'

services:
  db:
    image: mysql:5.5
    ports:
     - 3306
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: prereq_map
      MYSQL_USER: prereq_map
      MYSQL_PASSWORD: my_pass
  web:
    build: ..
    restart: on-failure
    volumes:
      - ../prereq_map:/app/prereq_map
      - ../docker:/app/project
    ports:
      - "8000:80"
    environment:
      DB: mysql
      RDS_PASSWORD: my_pass
      RDS_USER: prereq_map
      RDS_HOSTNAME: db
      RDS_DATABASE: prereq_map
      CACHE: memcached
      CACHE_NODE_0: cache:11211
      CACHE_NODE_1: cache:11211
      LOG: none
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
  cache:
    image: memcached
    ports:
      - 11211