ingress:
  enabled: false
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  tls:
    prereqmap:
      secretName: prereqmap.uw.edu-ingress-cert
      hosts:
        - prereqmap.uw.edu
  hosts:
    prereqmap:
      host: prereqmap.uw.edu
      paths:
        - "/"
database:
  engine: mysql
  name: prereq
  hostname: prereq-prod-db-service
  secretName: prereqmap.uw.edu-sql-secrets
externalService:
  enabled: true
  name: prereq-prod-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.12
  servicePort: 3306
repo: prereqmap
instance: prod
autoscaling:
  minReplicas: 2
  maxReplicas: 16
lifecycle:
  enabled: true
  preStop:
    enabled: true
readiness:
  enabled: true
targetAverageUtilization: 100
resources:
  limits:
    cpu: 1.0
    memory: 1280Mi
  requests:
    cpu: 256m
    memory: 1024Mi
affinity:
   podsSpanNodes: true
image:
  repository: gcr.io/uwit-mci-axdd/prereqmap
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
certs:
  mounted: true
  certPath: /certs/prereqmap.uw.edu-uwca.cert
  keyPath: /certs/prereqmap.uw.edu-uwca.key
  secretName: prereqmap.uw.edu-uwca-certs

environmentVariables:
  - name: ENV
    value: prod
  - name: CLUSTER_CNAME
    value: prereqmap.uw.edu
  - name: SWS_ENV
    value: PROD

externalSecrets:
  enabled: true
  secrets:
    - name: prereqmap.uw.edu-secrets
      externalKey: axdd/kv/data/prereq-map/prod/secrets
      data:
        - name: django-secret
          property: django-secret
        - name: email-host-password
          property: email-host-password
        - name: email-host-username
          property: email-host-username
        - name: google-analytics-key
          property: google-analytics-key
    - name: prereqmap.uw.edu-sql-secrets
      externalKey: axdd/kv/data/prereq-map/prod/sql-secrets
      data:
        - name: username
          property: username
        - name: password
          property: password
    - name: prereqmap.uw.edu-uwca-certs
      externalKey: axdd/kv/data/prereq-map/prod/uwca-certs
      data:
        - name: prereqmap.uw.edu-uwca.cert
          property: prereqmap.uw.edu-uwca.cert
        - name: prereqmap.uw.edu-uwca.key
          property: prereqmap.uw.edu-uwca.key

environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: prereqmap.uw.edu-secrets
    secretKey: django-secret
  gaKey:
    name: GOOGLE_ANALYTICS_KEY
    secretName: prereqmap.uw.edu-secrets
    secretKey: google-analytics-key
  emailHostUser:
    name: EMAIL_HOST_USER
    secretName: prereqmap.uw.edu-secrets
    secretKey: email-host-username
  emailHostPassword:
    name: EMAIL_HOST_PASSWORD
    secretName: prereqmap.uw.edu-secrets
    secretKey: email-host-password
