ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    prereqmap-test:
      secretName: test.prereqmap.uw.edu-4751ea1355a6e70e42ab3120fccc4d93
      hosts:
        - test.prereqmap.uw.edu
  hosts:
    prereqmap-test:
      host: test.prereqmap.uw.edu
      paths:
        - "/"
database:
  engine: mysql
  name: prereq
  hostname: prereq-test-db-service
  secretName: prereq-test-db
externalService:
  enabled: true
  name: prereq-test-db-service
  type: ClusterIP
  serviceAddress: 172.18.0.9
  servicePort: 3306
repo: prereqmap
instance: test
targetAverageUtilization: 100
resources:
  limits:
    cpu: 1.0
    memory: 1280Mi
  requests:
    cpu: 256m
    memory: 1024Mi
affinity:
   podsSpanNodes: true
image:
  repository: registry.hub.docker.com/acait/prereqmap
  tag: IMAGE_TAG
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
certs:
  mounted: true
  certPath: /certs/prereqmap.uw.edu-uwca.pem
  keyPath: /certs/prereqmap.uw.edu-uwca.key
  secretName: prereqmap-test-uwca-certs
environmentVariables:
  - name: ENV
    value: dev
  - name: SWS_ENV
    value: PROD
environmentVariablesSecrets:
  djangoSecret:
    name: DJANGO_SECRET
    secretName: prereqmap-test-django-secret
    secretKey: django-secret
  emailHostUser:
    name: EMAIL_HOST_USER
    secretName: email-post-credentials
    secretKey: username
  emailHostPassword:
    name: EMAIL_HOST_PASSWORD
    secretName: email-post-credentials
    secretKey: password
